name: Run Color Tests 2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@0.5.0



